{
  "openapi": "3.0.0",
  "info": {
    "title": "CodeBlue Project APIs Documentation",
    "description": "These APIs are made for CodeBlue project that mainly serve El Kasr El Ainy Outpatients Clinics",
    "version": "1.0.0",
    "contact": {
      "name": "API Support"
    }
  },
  "servers": [
    {
        "full base path":"https://api-gateway.yellowgrass-a3ce385a.westeurope.azurecontainerapps.io/api/v1",
      "url": "https://api-gateway.yellowgrass-a3ce385a.westeurope.azurecontainerapps.io",
      "description": "Production Server"
    }
  ],
  "tags": [
    {
      "name": "Auth",
      "description": "Authentication and Registration endpoints"
    },
    {
      "name": "ApiGateway",
      "description": "Gateway health and status"
    }
  ],
  "paths": {
    "/api/v1": {
      "get": {
        "tags": [
          "ApiGateway"
        ],
        "summary": "Gateway Root",
        "description": "Check API Gateway status",
        "responses": {
          "200": {
            "description": "Successful operation"
          }
        }
      }
    },
    "/api/v1/auth": {
      "get": {
        "tags": [
          "Auth"
        ],
        "summary": "Auth Check",
        "description": "Basic Auth endpoint check",
        "responses": {
          "200": {
            "description": "Successful operation"
          }
        }
      }
    },
    "/api/v1/auth/login": {
      "post": {
        "tags": [
          "Auth"
        ],
        "summary": "User Login",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/LoginDto"
              },
              "example": {
                "email": "john.doe@example.com",
                "password": "StrongPassword123!"
              }
            }
          },
          "required": true
        },
        "responses": {
          "201": {
            "description": "Login Successful"
          }
        }
      }
    },
    "/api/v1/auth/admin/create": {
      "post": {
        "tags": [
          "Auth"
        ],
        "summary": "Create Admin",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateAdminDto"
              },
              "example": {
                "firstName": "John",
                "lastName": "Doe",
                "language": 1,
                "socialSecurityNumber": "30202041234567",
                "email": "John@gmail.com",
                "phone": "+201015411320",
                "password": "StrongPassword123!"
              }
            }
          },
          "required": true
        },
        "responses": {
          "201": {
            "description": "Admin Created Successfully"
          }
        }
      }
    },
    "/api/v1/auth/doctor/create": {
      "post": {
        "tags": [
          "Auth"
        ],
        "summary": "Create Doctor",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateDoctorDto"
              },
              "example": {
                "firstName": "John",
                "lastName": "Doe",
                "language": 1,
                "socialSecurityNumber": "30202041234567",
                "email": "John@gmail.com",
                "phone": "+201015411320",
                "password": "StrongPassword123!",
                "speciality": "Dermatology"
              }
            }
          },
          "required": true
        },
        "responses": {
          "201": {
            "description": "Doctor Created Successfully"
          }
        }
      }
    },
    "/api/v1/auth/patient/create": {
      "post": {
        "tags": [
          "Auth"
        ],
        "summary": "Create Patient",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreatePatientDto"
              },
              "example": {
                "firstName": "John",
                "lastName": "Doe",
                "language": 1,
                "socialSecurityNumber": "30202041234567",
                "address": "53 El tahrir street, Dokki, Giza, Egypt",
                "job": "Math teacher"
              }
            }
          },
          "required": true
        },
        "responses": {
          "201": {
            "description": "Patient Created Successfully"
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Language": {
        "type": "integer",
        "description": "User language preference",
        "enum": [
          0,
          1
        ],
        "example": 1
      },
      "LoginDto": {
        "type": "object",
        "required": [
          "email",
          "password"
        ],
        "properties": {
          "email": {
            "type": "string",
            "description": "User email",
            "example": "john.doe@example.com"
          },
          "password": {
            "type": "string",
            "description": "User password",
            "example": "StrongPassword123!"
          }
        }
      },
      "CreateAdminDto": {
        "type": "object",
        "required": [
          "firstName",
          "lastName",
          "language",
          "socialSecurityNumber",
          "email",
          "phone",
          "password"
        ],
        "properties": {
          "firstName": {
            "type": "string",
            "description": "User first name",
            "example": "John"
          },
          "lastName": {
            "type": "string",
            "description": "User last name",
            "example": "Doe"
          },
          "language": {
            "$ref": "#/components/schemas/Language"
          },
          "socialSecurityNumber": {
            "type": "string",
            "description": "User national ID",
            "example": "30202041234567"
          },
          "email": {
            "type": "string",
            "description": "User email",
            "example": "John@gmail.com"
          },
          "phone": {
            "type": "string",
            "description": "User mobile phone number",
            "example": "+201015411320"
          },
          "password": {
            "type": "string",
            "description": "User password",
            "minLength": 8,
            "example": "StrongPassword123!"
          }
        }
      },
      "CreateDoctorDto": {
        "type": "object",
        "required": [
          "firstName",
          "lastName",
          "language",
          "socialSecurityNumber",
          "email",
          "phone",
          "password",
          "speciality"
        ],
        "properties": {
          "firstName": {
            "type": "string",
            "description": "User first name",
            "example": "John"
          },
          "lastName": {
            "type": "string",
            "description": "User last name",
            "example": "Doe"
          },
          "language": {
            "$ref": "#/components/schemas/Language"
          },
          "socialSecurityNumber": {
            "type": "string",
            "description": "User national ID",
            "example": "30202041234567"
          },
          "email": {
            "type": "string",
            "description": "User email",
            "example": "John@gmail.com"
          },
          "phone": {
            "type": "string",
            "description": "User mobile phone number",
            "example": "+201015411320"
          },
          "password": {
            "type": "string",
            "description": "User password",
            "minLength": 8,
            "example": "StrongPassword123!"
          },
          "speciality": {
            "type": "string",
            "description": "User medical speciality",
            "example": "Dermatology"
          }
        }
      },
      "CreatePatientDto": {
        "type": "object",
        "required": [
          "firstName",
          "lastName",
          "language",
          "socialSecurityNumber",
          "address",
          "job"
        ],
        "properties": {
          "firstName": {
            "type": "string",
            "description": "User first name",
            "example": "John"
          },
          "lastName": {
            "type": "string",
            "description": "User last name",
            "example": "Doe"
          },
          "language": {
            "$ref": "#/components/schemas/Language"
          },
          "socialSecurityNumber": {
            "type": "string",
            "description": "User national ID",
            "example": "30202041234567"
          },
          "address": {
            "type": "string",
            "description": "User address",
            "example": "53 El tahrir street, Dokki, Giza, Egypt"
          },
          "job": {
            "type": "string",
            "description": "User job",
            "example": "Math teacher"
          }
        }
      }
    }
  }
}